version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/p0037/src/app
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: nestjs-prisma-api
      MYSQL_ROOT_HOST: '%'
    volumes:
      - api-mysql-data:/var/lib/mysql/

volumes:
  api-mysql-data:
