version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3307/${MYSQL_DB}
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3307:3306
      - 33070:33060
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: nestjs-prisma-api
      MYSQL_ROOT_HOST: '%'
      TZ: 'America/Sao_Paulo'
    volumes:
      - api-mysql-data:/var/lib/mysql/

volumes:
  api-mysql-data:
